/* 高中數學公式總表 — 資料
 * 每一項：{ n: 名稱, h: 名稱下的提示(可省略), f: 標準公式(字串或多行陣列), c: 條件(可省略), t: 標籤(可省略) }
 * 字串中 $...$ 為數學式（KaTeX），其餘為一般文字。
 * 標籤 t：'A' = 只有數A、'B' = 只有數B、'選' = 高三選修。
 */
const r = String.raw;

const sections = [
  /* ============================ 高一上 ============================ */
  { part: '高一上・第一冊', title: '數與式', items: [
    { n: '完全平方', h: r`$(a\pm b)^2$`, f: r`$(a\pm b)^2=a^2\pm 2ab+b^2$` },
    { n: '平方差', h: r`$a^2-b^2$`, f: r`$a^2-b^2=(a+b)(a-b)$` },
    { n: '和、差的立方', h: r`$(a\pm b)^3$`, f: r`$(a\pm b)^3=a^3\pm 3a^2b+3ab^2\pm b^3$` },
    { n: '立方和、立方差', h: r`$a^3\pm b^3$`, f: r`$a^3\pm b^3=(a\pm b)(a^2\mp ab+b^2)$` },
    { n: '三數和的平方', h: r`$(a+b+c)^2$`, f: r`$(a+b+c)^2=a^2+b^2+c^2+2ab+2bc+2ca$` },
    { n: '分母有理化', h: r`$1/(\sqrt a+\sqrt b)$`, f: r`$\dfrac{1}{\sqrt a+\sqrt b}=\dfrac{\sqrt a-\sqrt b}{a-b}$` },
    { n: '雙重根式', h: r`$\sqrt{(a+b)\pm 2\sqrt{ab}}$`, f: r`$\sqrt{(a+b)\pm 2\sqrt{ab}}=\sqrt a\pm\sqrt b$`, c: r`$a>b>0$` },
    { n: '絕對值不等式（小於）', h: r`$|x-a|<r$`, f: r`$|x-a|<r \iff a-r<x<a+r$`, c: r`$r>0$` },
    { n: '絕對值不等式（大於）', h: r`$|x-a|>r$`, f: r`$|x-a|>r \iff x<a-r$ 或 $x>a+r$`, c: r`$r>0$` },
    { n: '數線上的分點', h: r`$A(a)$、$B(b)$，$\overline{AP}:\overline{PB}=m:n$`, f: r`$P=\dfrac{na+mb}{m+n}$` },
    { n: '算幾不等式', f: r`$\dfrac{a+b}{2}\ge\sqrt{ab}$，等號成立 $\iff a=b$`, c: r`$a,b\ge 0$` },
  ]},
  { part: '高一上・第一冊', title: '指數與對數', items: [
    { n: '指數律', f: r`$a^m a^n=a^{m+n}$，$\dfrac{a^m}{a^n}=a^{m-n}$，$(a^m)^n=a^{mn}$，$(ab)^n=a^nb^n$` },
    { n: '零次方、負次方', f: r`$a^0=1$，$a^{-n}=\dfrac{1}{a^n}$`, c: r`$a\ne 0$` },
    { n: '有理數次方', h: r`$a^{\frac mn}$`, f: r`$a^{\frac{m}{n}}=\sqrt[n]{a^m}$`, c: r`$a>0$` },
    { n: '對數的定義', f: r`$\log_a b=c \iff a^c=b$`, c: r`$a>0,\ a\ne1,\ b>0$` },
    { n: '對數的乘、除', f: r`$\log_a(MN)=\log_a M+\log_a N$，$\log_a\dfrac MN=\log_a M-\log_a N$` },
    { n: '對數的次方', h: r`$\log_a M^p$`, f: r`$\log_a M^p=p\log_a M$` },
    { n: '換底公式', h: r`$\log_a b$`, f: r`$\log_a b=\dfrac{\log_c b}{\log_c a}=\dfrac{\log b}{\log a}$` },
    { n: '換底推論', h: r`$\log_{a^m} b^n$`, f: r`$\log_{a^m} b^n=\dfrac nm\log_a b$` },
    { n: '倒數關係', h: r`$\log_a b\cdot\log_b a$`, f: r`$\log_a b\cdot\log_b a=1$` },
    { n: '指數與對數互消', h: r`$a^{\log_a b}$`, f: r`$a^{\log_a b}=b$` },
    { n: '整數部分的位數', h: r`$x\ge1$ 的整數部分有 $n$ 位`, f: r`$n-1\le\log x<n$` },
    { n: '小數點後第幾位不為 0', h: r`$0<x<1$，小數點後第 $n$ 位首次不為 $0$`, f: r`$-n\le\log x<-n+1$` },
    { n: '指數、對數函數的單調性', f: [r`$a>1$：$y=a^x$、$y=\log_a x$ 都遞增；$0<a<1$：都遞減`, r`$y=a^x$ 過 $(0,1)$，$y=\log_a x$ 過 $(1,0)$，兩圖形對稱於 $y=x$`] },
    { n: '複利（本利和）', h: r`本金 $P$，每期利率 $r$，$n$ 期`, f: r`本利和 $=P(1+r)^n$` },
    { n: '半衰期', h: r`原量 $m_0$，半衰期 $T$，經過 $t$`, f: r`剩餘量 $=m_0\left(\dfrac12\right)^{t/T}$` },
  ]},
  { part: '高一上・第一冊', title: '多項式函數', items: [
    { n: '除法原理', f: r`$f(x)=g(x)\,Q(x)+r(x)$，$\deg r(x)<\deg g(x)$ 或 $r(x)=0$` },
    { n: '餘式定理', f: r`$f(x)$ 除以 $x-a$ 的餘式 $=f(a)$；除以 $ax-b$ 的餘式 $=f\!\left(\dfrac ba\right)$` },
    { n: '因式定理', f: r`$x-a$ 是 $f(x)$ 的因式 $\iff f(a)=0$` },
    { n: '一次因式檢驗法', f: r`整係數 $f(x)=a_nx^n+\cdots+a_0$，若 $ax-b$（$a,b$ 互質）為因式 $\Rightarrow a\mid a_n$ 且 $b\mid a_0$` },
    { n: '二次函數配方', h: r`$ax^2+bx+c$`, f: r`$ax^2+bx+c=a\left(x+\dfrac{b}{2a}\right)^2-\dfrac{b^2-4ac}{4a}$` },
    { n: '頂點與對稱軸', h: r`$y=ax^2+bx+c$`, f: r`頂點 $\left(-\dfrac{b}{2a},\,-\dfrac{b^2-4ac}{4a}\right)$，對稱軸 $x=-\dfrac{b}{2a}$` },
    { n: '公式解', h: r`$ax^2+bx+c=0$`, f: r`$x=\dfrac{-b\pm\sqrt{b^2-4ac}}{2a}$` },
    { n: '判別式', h: r`$D=b^2-4ac$`, f: r`$D>0$ 相異兩實根；$D=0$ 重根；$D<0$ 沒有實根（兩共軛虛根）` },
    { n: '根與係數（二次）', h: r`$ax^2+bx+c=0$ 兩根 $\alpha,\beta$`, f: r`$\alpha+\beta=-\dfrac ba$，$\alpha\beta=\dfrac ca$` },
    { n: '根與係數（三次）', h: r`$ax^3+bx^2+cx+d=0$`, f: r`$\alpha+\beta+\gamma=-\dfrac ba$，$\alpha\beta+\beta\gamma+\gamma\alpha=\dfrac ca$，$\alpha\beta\gamma=-\dfrac da$` },
    { n: '二次不等式', h: r`$\alpha<\beta$`, f: [r`$(x-\alpha)(x-\beta)<0\iff\alpha<x<\beta$`, r`$(x-\alpha)(x-\beta)>0\iff x<\alpha$ 或 $x>\beta$`] },
    { n: '二次式恆正', h: r`$ax^2+bx+c>0$ 對所有實數 $x$ 成立`, f: r`$a>0$ 且 $b^2-4ac<0$` },
    { n: '三次函數的對稱中心', h: r`$y=ax^3+bx^2+cx+d$`, f: r`對稱中心的 $x$ 坐標 $=-\dfrac{b}{3a}$` },
    { n: '三次函數的標準式', f: r`$f(x)=a(x-h)^3+p(x-h)+k$：對稱中心 $(h,k)$，在 $x=h$ 附近的一次近似 $y=p(x-h)+k$` },
    { n: '拉格朗日插值', h: r`過 $(x_1,y_1),(x_2,y_2),(x_3,y_3)$`, f: r`$f(x)=y_1\dfrac{(x-x_2)(x-x_3)}{(x_1-x_2)(x_1-x_3)}+y_2\dfrac{(x-x_1)(x-x_3)}{(x_2-x_1)(x_2-x_3)}+y_3\dfrac{(x-x_1)(x-x_2)}{(x_3-x_1)(x_3-x_2)}$` },
  ]},
  { part: '高一上・第一冊', title: '直線與圓', items: [
    { n: '兩點距離', f: r`$\overline{AB}=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$` },
    { n: '分點公式', h: r`$\overline{AP}:\overline{PB}=m:n$`, f: r`$P=\left(\dfrac{nx_1+mx_2}{m+n},\ \dfrac{ny_1+my_2}{m+n}\right)$` },
    { n: '三角形重心', f: r`$G=\left(\dfrac{x_1+x_2+x_3}{3},\ \dfrac{y_1+y_2+y_3}{3}\right)$` },
    { n: '斜率', f: r`$m=\dfrac{y_2-y_1}{x_2-x_1}=\tan\theta$（$\theta$ 為斜角）` },
    { n: '兩直線平行、垂直', f: r`平行 $\iff m_1=m_2$；垂直 $\iff m_1m_2=-1$` },
    { n: '點斜式', f: r`$y-y_0=m(x-x_0)$` },
    { n: '斜截式', f: r`$y=mx+b$（$b$ 為 $y$ 截距）` },
    { n: '截距式', f: r`$\dfrac xa+\dfrac yb=1$（$x$ 截距 $a$、$y$ 截距 $b$）` },
    { n: '一般式的斜率、法向量', h: r`$ax+by+c=0$`, f: r`斜率 $-\dfrac ab$，法向量 $(a,b)$，方向向量 $(b,-a)$` },
    { n: '點到直線距離', h: r`$P(x_0,y_0)$ 到 $ax+by+c=0$`, f: r`$d=\dfrac{|ax_0+by_0+c|}{\sqrt{a^2+b^2}}$` },
    { n: '兩平行線距離', h: r`$ax+by+c_1=0$、$ax+by+c_2=0$`, f: r`$d=\dfrac{|c_1-c_2|}{\sqrt{a^2+b^2}}$` },
    { n: '圓的標準式', f: r`$(x-h)^2+(y-k)^2=r^2$，圓心 $(h,k)$，半徑 $r$` },
    { n: '圓的一般式', h: r`$x^2+y^2+dx+ey+f=0$`, f: r`圓心 $\left(-\dfrac d2,-\dfrac e2\right)$，半徑 $\dfrac{\sqrt{d^2+e^2-4f}}{2}$` },
    { n: '直線與圓的關係', h: r`$d$ = 圓心到直線距離`, f: r`$d<r$ 交於兩點；$d=r$ 相切；$d>r$ 不相交` },
    { n: '圓上一點的切線', h: r`$(x_0,y_0)$ 在圓上`, f: r`$(x_0-h)(x-h)+(y_0-k)(y-k)=r^2$` },
    { n: '圓外一點的切線段長', h: r`$(x_0,y_0)$ 在圓外`, f: r`$\sqrt{(x_0-h)^2+(y_0-k)^2-r^2}$` },
  ]},

  /* ============================ 高一下 ============================ */
  { part: '高一下・第二冊', title: '數列與級數', items: [
    { n: '等差數列一般項', f: r`$a_n=a_1+(n-1)d$` },
    { n: '等差級數和', f: r`$S_n=\dfrac{n(a_1+a_n)}{2}=\dfrac{n\left[2a_1+(n-1)d\right]}{2}$` },
    { n: '等差中項', f: r`$a,b,c$ 成等差 $\iff 2b=a+c$` },
    { n: '等比數列一般項', f: r`$a_n=a_1r^{n-1}$` },
    { n: '等比級數和', f: r`$S_n=\dfrac{a_1(1-r^n)}{1-r}$（$r\ne1$）；$r=1$ 時 $S_n=na_1$` },
    { n: '等比中項', f: r`$a,b,c$ 成等比 $\iff b^2=ac$` },
    { n: '足碼性質', h: r`$m+n=p+q$`, f: r`等差：$a_m+a_n=a_p+a_q$；等比：$a_ma_n=a_pa_q$` },
    { n: '連續整數和', h: r`$\sum_{k=1}^n k$`, f: r`$1+2+\cdots+n=\dfrac{n(n+1)}{2}$` },
    { n: '平方和', h: r`$\sum_{k=1}^n k^2$`, f: r`$1^2+2^2+\cdots+n^2=\dfrac{n(n+1)(2n+1)}{6}$` },
    { n: '立方和', h: r`$\sum_{k=1}^n k^3$`, f: r`$1^3+2^3+\cdots+n^3=\left[\dfrac{n(n+1)}{2}\right]^2$` },
    { n: 'Σ 的性質', f: r`$\sum(a_k\pm b_k)=\sum a_k\pm\sum b_k$，$\sum ca_k=c\sum a_k$，$\sum_{k=1}^{n} c=nc$` },
    { n: '分項對消', h: r`$1/[k(k+1)]$`, f: r`$\dfrac{1}{k(k+1)}=\dfrac1k-\dfrac{1}{k+1}$` },
  ]},
  { part: '高一下・第二冊', title: '數據分析', items: [
    { n: '算術平均數', f: r`$\mu=\dfrac{x_1+x_2+\cdots+x_n}{n}$` },
    { n: '加權平均數', f: r`$\dfrac{w_1x_1+w_2x_2+\cdots+w_nx_n}{w_1+w_2+\cdots+w_n}$` },
    { n: '幾何平均數', f: r`$\sqrt[n]{x_1x_2\cdots x_n}$` },
    { n: '平均成長率', h: r`各期成長率 $r_1,\dots,r_n$`, f: r`$\sqrt[n]{(1+r_1)(1+r_2)\cdots(1+r_n)}-1$` },
    { n: '中位數', f: r`$n$ 為奇數：第 $\dfrac{n+1}{2}$ 筆；$n$ 為偶數：第 $\dfrac n2$、$\dfrac n2+1$ 筆的平均` },
    { n: '第 k 百分位數', h: r`資料由小到大，算 $n\times k\%$`, f: r`是整數 $m$ $\Rightarrow$ 第 $m$、$m+1$ 筆的平均；不是整數 $\Rightarrow$ 取無條件進位那一筆` },
    { n: '全距、四分位距', f: r`全距 $=$ 最大值 $-$ 最小值；四分位距 $IQR=Q_3-Q_1$` },
    { n: '變異數', f: r`$\sigma^2=\dfrac1n\sum(x_i-\mu)^2=\dfrac1n\sum x_i^2-\mu^2$` },
    { n: '標準差', f: r`$\sigma=\sqrt{\dfrac1n\sum(x_i-\mu)^2}=\sqrt{\dfrac1n\sum x_i^2-\mu^2}$` },
    { n: '資料的線性變換', h: r`$y_i=ax_i+b$`, f: r`$\mu_y=a\mu_x+b$，$\sigma_y=|a|\,\sigma_x$` },
    { n: '標準化', f: r`$z_i=\dfrac{x_i-\mu}{\sigma}$（平均 $0$、標準差 $1$）` },
    { n: '相關係數', f: r`$r=\dfrac{\sum(x_i-\mu_x)(y_i-\mu_y)}{\sqrt{\sum(x_i-\mu_x)^2}\sqrt{\sum(y_i-\mu_y)^2}}=\dfrac{\sum(x_i-\mu_x)(y_i-\mu_y)}{n\,\sigma_x\sigma_y}$` },
    { n: '相關係數（標準化）', f: r`$r=\dfrac1n\sum z_{x_i}\,z_{y_i}$` },
    { n: '迴歸直線（最適直線）', f: r`$y-\mu_y=r\,\dfrac{\sigma_y}{\sigma_x}(x-\mu_x)$，斜率 $=r\,\dfrac{\sigma_y}{\sigma_x}$` },
    { n: '變換後的相關係數', h: r`$x'=ax+b$，$y'=cy+d$`, f: r`$ac>0\Rightarrow r'=r$；$ac<0\Rightarrow r'=-r$` },
  ]},
  { part: '高一下・第二冊', title: '排列組合與機率', items: [
    { n: '取捨原理（兩集合）', f: r`$n(A\cup B)=n(A)+n(B)-n(A\cap B)$` },
    { n: '取捨原理（三集合）', f: [r`$n(A\cup B\cup C)=n(A)+n(B)+n(C)$`, r`$\qquad-n(A\cap B)-n(B\cap C)-n(C\cap A)+n(A\cap B\cap C)$`] },
    { n: '笛摩根定律', f: r`$(A\cup B)'=A'\cap B'$，$(A\cap B)'=A'\cup B'$` },
    { n: '排列', h: r`$P^n_k$`, f: r`$P^n_k=\dfrac{n!}{(n-k)!}=n(n-1)\cdots(n-k+1)$` },
    { n: '重複排列', h: r`$k$ 個位置，每個有 $n$ 種選擇`, f: r`$n^k$` },
    { n: '不盡相異物排列', h: r`$n$ 個中有 $p$ 個、$q$ 個…相同`, f: r`$\dfrac{n!}{p!\,q!\,r!\cdots}$` },
    { n: '環狀排列', h: r`$n$ 個相異物排成一圈`, f: r`$\dfrac{n!}{n}=(n-1)!$` },
    { n: '組合', h: r`$C^n_k$`, f: r`$C^n_k=\dfrac{n!}{k!\,(n-k)!}$` },
    { n: '組合的對稱性', f: r`$C^n_k=C^n_{n-k}$` },
    { n: '巴斯卡定理', f: r`$C^n_k=C^{n-1}_k+C^{n-1}_{k-1}$` },
    { n: '重複組合', h: r`$H^n_k$`, f: r`$H^n_k=C^{n+k-1}_k$` },
    { n: '二項式定理', h: r`$(a+b)^n$`, f: r`$(a+b)^n=\sum_{k=0}^{n}C^n_k\,a^{n-k}b^k$` },
    { n: '二項展開的一般項', h: r`第 $k+1$ 項`, f: r`$T_{k+1}=C^n_k\,a^{n-k}b^k$` },
    { n: '二項係數和', f: r`$C^n_0+C^n_1+\cdots+C^n_n=2^n$` },
    { n: '古典機率', f: r`$P(A)=\dfrac{n(A)}{n(S)}$` },
    { n: '餘事件', f: r`$P(A')=1-P(A)$` },
    { n: '和事件', f: r`$P(A\cup B)=P(A)+P(B)-P(A\cap B)$` },
    { n: '期望值', f: r`$E=x_1p_1+x_2p_2+\cdots+x_np_n$` },
  ]},
  { part: '高一下・第二冊', title: '三角比', items: [
    { n: '直角三角形的三角比', f: r`$\sin\theta=\dfrac{\text{對邊}}{\text{斜邊}}$，$\cos\theta=\dfrac{\text{鄰邊}}{\text{斜邊}}$，$\tan\theta=\dfrac{\text{對邊}}{\text{鄰邊}}$` },
    { n: '平方關係', f: r`$\sin^2\theta+\cos^2\theta=1$` },
    { n: '商數關係', f: r`$\tan\theta=\dfrac{\sin\theta}{\cos\theta}$` },
    { n: '餘角關係', h: r`$90^\circ-\theta$`, f: r`$\sin(90^\circ-\theta)=\cos\theta$，$\cos(90^\circ-\theta)=\sin\theta$` },
    { n: '廣義角的三角比', h: r`終邊上一點 $P(x,y)$，$r=\sqrt{x^2+y^2}$`, f: r`$\sin\theta=\dfrac yr$，$\cos\theta=\dfrac xr$，$\tan\theta=\dfrac yx$` },
    { n: '各象限的正負', f: r`第一象限全正；第二 $\sin$ 正；第三 $\tan$ 正；第四 $\cos$ 正` },
    { n: '補角關係', h: r`$180^\circ-\theta$`, f: [r`$\sin(180^\circ-\theta)=\sin\theta$，$\cos(180^\circ-\theta)=-\cos\theta$`, r`$\tan(180^\circ-\theta)=-\tan\theta$`] },
    { n: '負角關係', h: r`$-\theta$`, f: r`$\sin(-\theta)=-\sin\theta$，$\cos(-\theta)=\cos\theta$，$\tan(-\theta)=-\tan\theta$` },
    { n: '三角形面積（兩邊夾角）', f: r`$\triangle=\dfrac12ab\sin C$` },
    { n: '海龍公式', f: r`$\triangle=\sqrt{s(s-a)(s-b)(s-c)}$，$s=\dfrac{a+b+c}{2}$` },
    { n: '正弦定理', f: r`$\dfrac{a}{\sin A}=\dfrac{b}{\sin B}=\dfrac{c}{\sin C}=2R$（$R$ 為外接圓半徑）` },
    { n: '餘弦定理', f: r`$c^2=a^2+b^2-2ab\cos C$，$\cos C=\dfrac{a^2+b^2-c^2}{2ab}$` },
    { n: '內切圓半徑', f: r`$\triangle=rs$（$s$ 為半周長）` },
    { n: '外接圓半徑', f: r`$R=\dfrac{abc}{4\triangle}$` },
    { n: '中線定理', h: r`$M$ 為 $\overline{BC}$ 中點`, f: r`$\overline{AB}^2+\overline{AC}^2=2\left(\overline{AM}^2+\overline{BM}^2\right)$` },
    { n: '角平分線性質', h: r`$\overline{AD}$ 平分 $\angle A$`, f: r`$\overline{BD}:\overline{DC}=\overline{AB}:\overline{AC}$` },
  ]},

  /* ============================ 高二 ============================ */
  { part: '高二・第三冊', title: '三角函數', items: [
    { n: '弧度與角度', f: r`$\pi\ (\text{弧度})=180^\circ$，$1\ \text{弧度}=\dfrac{180^\circ}{\pi}$` },
    { n: '弧長、扇形面積', h: r`半徑 $r$，圓心角 $\theta$（弧度）`, f: r`$s=r\theta$，$A=\dfrac12r^2\theta=\dfrac12rs$` },
    { n: '正弦型函數', h: r`$y=a\sin(bx+c)+d$`, f: r`振幅 $|a|$，週期 $\dfrac{2\pi}{|b|}$，最大值 $d+|a|$，最小值 $d-|a|$` },
    { n: '正切函數的週期', h: r`$y=\tan(bx)$`, f: r`週期 $\dfrac{\pi}{|b|}$` },
    { n: '和角公式（sin）', h: r`$\sin(\alpha\pm\beta)$`, f: r`$\sin(\alpha\pm\beta)=\sin\alpha\cos\beta\pm\cos\alpha\sin\beta$` },
    { n: '和角公式（cos）', h: r`$\cos(\alpha\pm\beta)$`, f: r`$\cos(\alpha\pm\beta)=\cos\alpha\cos\beta\mp\sin\alpha\sin\beta$` },
    { n: '和角公式（tan）', h: r`$\tan(\alpha\pm\beta)$`, f: r`$\tan(\alpha\pm\beta)=\dfrac{\tan\alpha\pm\tan\beta}{1\mp\tan\alpha\tan\beta}$` },
    { n: '二倍角（sin）', h: r`$\sin2\theta$`, f: r`$\sin2\theta=2\sin\theta\cos\theta$` },
    { n: '二倍角（cos）', h: r`$\cos2\theta$`, f: r`$\cos2\theta=\cos^2\theta-\sin^2\theta=2\cos^2\theta-1=1-2\sin^2\theta$` },
    { n: '二倍角（tan）', h: r`$\tan2\theta$`, f: r`$\tan2\theta=\dfrac{2\tan\theta}{1-\tan^2\theta}$` },
    { n: '半角（降次）公式', f: r`$\sin^2\theta=\dfrac{1-\cos2\theta}{2}$，$\cos^2\theta=\dfrac{1+\cos2\theta}{2}$` },
    { n: '三倍角公式', t: 'A', f: r`$\sin3\theta=3\sin\theta-4\sin^3\theta$，$\cos3\theta=4\cos^3\theta-3\cos\theta$` },
    { n: '正餘弦疊合', h: r`$a\sin\theta+b\cos\theta$`, f: r`$=\sqrt{a^2+b^2}\,\sin(\theta+\varphi)$，其中 $\cos\varphi=\dfrac{a}{\sqrt{a^2+b^2}}$，$\sin\varphi=\dfrac{b}{\sqrt{a^2+b^2}}$` },
    { n: '疊合的最大、最小值', f: r`$-\sqrt{a^2+b^2}\le a\sin\theta+b\cos\theta\le\sqrt{a^2+b^2}$` },
    { n: '極坐標換直角坐標', h: r`$[\,r,\theta\,]$`, f: r`$(x,y)=(r\cos\theta,\ r\sin\theta)$，$r=\sqrt{x^2+y^2}$` },
  ]},
  { part: '高二・第三冊', title: '平面向量', items: [
    { n: '向量的坐標與長度', f: r`$\overrightarrow{AB}=(x_2-x_1,\ y_2-y_1)$，$|(a,b)|=\sqrt{a^2+b^2}$` },
    { n: '分點公式（向量）', h: r`$\overline{AP}:\overline{PB}=m:n$`, f: r`$\overrightarrow{OP}=\dfrac{n}{m+n}\overrightarrow{OA}+\dfrac{m}{m+n}\overrightarrow{OB}$` },
    { n: '三點共線', h: r`$\overrightarrow{OP}=\alpha\overrightarrow{OA}+\beta\overrightarrow{OB}$`, f: r`$P$ 在直線 $AB$ 上 $\iff\alpha+\beta=1$` },
    { n: '內積的定義', f: r`$\vec a\cdot\vec b=|\vec a|\,|\vec b|\cos\theta$` },
    { n: '內積的坐標算法', f: r`$(x_1,y_1)\cdot(x_2,y_2)=x_1x_2+y_1y_2$` },
    { n: '兩向量夾角', f: r`$\cos\theta=\dfrac{\vec a\cdot\vec b}{|\vec a|\,|\vec b|}$` },
    { n: '垂直、平行', f: r`$\vec a\perp\vec b\iff\vec a\cdot\vec b=0$；$\vec a\parallel\vec b\iff x_1y_2-x_2y_1=0$` },
    { n: '正射影', h: r`$\vec a$ 在 $\vec b$ 上`, f: r`正射影 $=\dfrac{\vec a\cdot\vec b}{|\vec b|^2}\,\vec b$，正射影長 $=\dfrac{|\vec a\cdot\vec b|}{|\vec b|}$` },
    { n: '柯西不等式（二維）', f: r`$(x_1x_2+y_1y_2)^2\le(x_1^2+y_1^2)(x_2^2+y_2^2)$，等號 $\iff$ 兩向量平行` },
    { n: '三角形面積（向量）', h: r`$\vec a=(x_1,y_1)$，$\vec b=(x_2,y_2)$`, f: r`$\triangle=\dfrac12\sqrt{|\vec a|^2|\vec b|^2-(\vec a\cdot\vec b)^2}=\dfrac12\,|x_1y_2-x_2y_1|$` },
    { n: '二階行列式', f: r`$\begin{vmatrix}a&b\\c&d\end{vmatrix}=ad-bc$` },
    { n: '克拉瑪公式', h: r`$\begin{cases}ax+by=e\\cx+dy=f\end{cases}$`, f: r`$\Delta=\begin{vmatrix}a&b\\c&d\end{vmatrix}$，$\Delta_x=\begin{vmatrix}e&b\\f&d\end{vmatrix}$，$\Delta_y=\begin{vmatrix}a&e\\c&f\end{vmatrix}$，$x=\dfrac{\Delta_x}{\Delta}$，$y=\dfrac{\Delta_y}{\Delta}$` },
    { n: '直線的參數式', f: r`$(x,y)=(x_0,y_0)+t(a,b)$，$t\in\mathbb R$` },
  ]},
  { part: '高二・第四冊', title: '空間向量與空間坐標', items: [
    { n: '空間兩點距離', f: r`$\sqrt{(x_2-x_1)^2+(y_2-y_1)^2+(z_2-z_1)^2}$` },
    { n: '空間向量內積', f: r`$\vec a\cdot\vec b=x_1x_2+y_1y_2+z_1z_2=|\vec a|\,|\vec b|\cos\theta$` },
    { n: '柯西不等式（三維）', f: r`$(a_1b_1+a_2b_2+a_3b_3)^2\le(a_1^2+a_2^2+a_3^2)(b_1^2+b_2^2+b_3^2)$` },
    { n: '外積', t: 'A', h: r`$\vec a=(a_1,a_2,a_3)$，$\vec b=(b_1,b_2,b_3)$`, f: r`$\vec a\times\vec b=\left(\begin{vmatrix}a_2&a_3\\b_2&b_3\end{vmatrix},\begin{vmatrix}a_3&a_1\\b_3&b_1\end{vmatrix},\begin{vmatrix}a_1&a_2\\b_1&b_2\end{vmatrix}\right)$` },
    { n: '外積的長度', t: 'A', f: r`$|\vec a\times\vec b|=|\vec a|\,|\vec b|\sin\theta=$ 平行四邊形面積` },
    { n: '三階行列式', t: 'A', f: r`$\begin{vmatrix}a_1&a_2&a_3\\b_1&b_2&b_3\\c_1&c_2&c_3\end{vmatrix}=a_1b_2c_3+a_2b_3c_1+a_3b_1c_2-a_3b_2c_1-a_2b_1c_3-a_1b_3c_2$` },
    { n: '平行六面體、四面體體積', t: 'A', h: r`由 $\vec a,\vec b,\vec c$ 張成`, f: r`平行六面體 $=\left|\det(\vec a,\vec b,\vec c)\right|$；四面體 $=\dfrac16\left|\det(\vec a,\vec b,\vec c)\right|$` },
    { n: '平面方程式（點法式）', t: 'A', h: r`過 $(x_0,y_0,z_0)$，法向量 $(a,b,c)$`, f: r`$a(x-x_0)+b(y-y_0)+c(z-z_0)=0$` },
    { n: '平面截距式', t: 'A', f: r`$\dfrac xa+\dfrac yb+\dfrac zc=1$` },
    { n: '點到平面距離', t: 'A', h: r`$(x_0,y_0,z_0)$ 到 $ax+by+cz+d=0$`, f: r`$\dfrac{|ax_0+by_0+cz_0+d|}{\sqrt{a^2+b^2+c^2}}$` },
    { n: '兩平行平面距離', t: 'A', f: r`$\dfrac{|d_1-d_2|}{\sqrt{a^2+b^2+c^2}}$` },
    { n: '兩平面夾角', t: 'A', f: r`$\cos\theta=\pm\dfrac{\vec n_1\cdot\vec n_2}{|\vec n_1|\,|\vec n_2|}$（法向量夾角或其補角）` },
    { n: '空間直線', t: 'A', h: r`過 $(x_0,y_0,z_0)$，方向 $(a,b,c)$`, f: r`參數式 $(x_0+at,\ y_0+bt,\ z_0+ct)$；比例式 $\dfrac{x-x_0}{a}=\dfrac{y-y_0}{b}=\dfrac{z-z_0}{c}$` },
    { n: '球面方程式', f: r`$(x-h)^2+(y-k)^2+(z-l)^2=r^2$` },
    { n: '經緯度坐標', t: 'B', h: r`半徑 $R$，北緯 $\theta$、東經 $\varphi$`, f: r`$(R\cos\theta\cos\varphi,\ R\cos\theta\sin\varphi,\ R\sin\theta)$` },
    { n: '緯線長', t: 'B', h: r`北緯 $\theta$`, f: r`$2\pi R\cos\theta$` },
    { n: '球面上兩點的大圓劣弧長', f: r`$R\times\angle AOB$（$\angle AOB$ 用弧度）` },
  ]},
  { part: '高二・第四冊', title: '矩陣', items: [
    { n: '矩陣乘法', f: r`$A_{m\times n}B_{n\times p}=C_{m\times p}$，$c_{ij}=a_{i1}b_{1j}+a_{i2}b_{2j}+\cdots+a_{in}b_{nj}$` },
    { n: '二階反方陣', h: r`$A=\begin{bmatrix}a&b\\c&d\end{bmatrix}$`, f: r`$A^{-1}=\dfrac{1}{ad-bc}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}$` },
    { n: '反方陣存在的條件', f: r`$A^{-1}$ 存在 $\iff\det A\ne0$` },
    { n: '用反方陣解聯立', f: r`$AX=B\Rightarrow X=A^{-1}B$` },
    { n: '乘積的反方陣、行列式', f: r`$(AB)^{-1}=B^{-1}A^{-1}$，$\det(AB)=\det A\cdot\det B$` },
    { n: '轉移矩陣', t: 'A', f: r`$X_n=A^nX_0$；穩定狀態 $X$ 滿足 $AX=X$（各元素和為 $1$）` },
  ]},
  { part: '高二・第四冊', title: '條件機率', items: [
    { n: '條件機率', f: r`$P(A\mid B)=\dfrac{P(A\cap B)}{P(B)}$` },
    { n: '乘法定理', f: r`$P(A\cap B)=P(A)\,P(B\mid A)$` },
    { n: '獨立事件', f: r`$A,B$ 獨立 $\iff P(A\cap B)=P(A)\,P(B)$` },
    { n: '全機率（分割）', f: r`$P(B)=P(A)\,P(B\mid A)+P(A')\,P(B\mid A')$` },
    { n: '貝氏定理', f: r`$P(A\mid B)=\dfrac{P(A)\,P(B\mid A)}{P(A)\,P(B\mid A)+P(A')\,P(B\mid A')}$` },
  ]},
  { part: '高二・第四冊', title: '圓錐曲線', items: [
    { n: '圓錐截痕的判別', t: 'B', h: r`平面與軸的夾角 $\varphi$，半頂角 $\alpha$`, f: r`$\varphi=90^\circ$ 圓；$\alpha<\varphi<90^\circ$ 橢圓；$\varphi=\alpha$ 拋物線；$\varphi<\alpha$ 雙曲線` },
    { n: '拋物線（左右開口）', h: r`$y^2=4cx$`, f: r`焦點 $(c,0)$，準線 $x=-c$，正焦弦長 $4|c|$` },
    { n: '拋物線（上下開口）', h: r`$x^2=4cy$`, f: r`焦點 $(0,c)$，準線 $y=-c$，正焦弦長 $4|c|$` },
    { n: '橢圓', h: r`$x^2/a^2+y^2/b^2=1$，$a>b>0$`, f: r`$c^2=a^2-b^2$，焦點 $(\pm c,0)$，$\overline{PF_1}+\overline{PF_2}=2a$` },
    { n: '橢圓的軸長、正焦弦', f: r`長軸 $2a$，短軸 $2b$，正焦弦長 $\dfrac{2b^2}{a}$` },
    { n: '雙曲線', h: r`$x^2/a^2-y^2/b^2=1$`, f: r`$c^2=a^2+b^2$，焦點 $(\pm c,0)$，$\left|\overline{PF_1}-\overline{PF_2}\right|=2a$` },
    { n: '雙曲線的漸近線、正焦弦', f: r`漸近線 $y=\pm\dfrac bax$，正焦弦長 $\dfrac{2b^2}{a}$` },
  ]},

  /* ============================ 高三選修 ============================ */
  { part: '高三・選修（數甲／數乙）', elective: true, title: '機率分布', items: [
    { n: '隨機變數的期望值', f: r`$E(X)=\sum x_i\,p_i$` },
    { n: '隨機變數的變異數', f: r`$\mathrm{Var}(X)=\sum(x_i-\mu)^2p_i=E(X^2)-\left[E(X)\right]^2$` },
    { n: '期望值、變異數的線性', f: r`$E(aX+b)=aE(X)+b$，$\mathrm{Var}(aX+b)=a^2\,\mathrm{Var}(X)$` },
    { n: '二項分布', h: r`$X\sim B(n,p)$`, f: r`$P(X=k)=C^n_k\,p^k(1-p)^{n-k}$` },
    { n: '二項分布的期望值、變異數', f: r`$E(X)=np$，$\mathrm{Var}(X)=np(1-p)$` },
    { n: '幾何分布', h: r`第 $k$ 次才第一次成功`, f: r`$P(X=k)=(1-p)^{k-1}p$，$E(X)=\dfrac1p$，$\mathrm{Var}(X)=\dfrac{1-p}{p^2}$` },
  ]},
  { part: '高三・選修（數甲／數乙）', elective: true, title: '三角與複數', items: [
    { n: '和差化積', f: [r`$\sin\alpha+\sin\beta=2\sin\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2}$`, r`$\sin\alpha-\sin\beta=2\cos\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2}$`, r`$\cos\alpha+\cos\beta=2\cos\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2}$`, r`$\cos\alpha-\cos\beta=-2\sin\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2}$`] },
    { n: '積化和差', f: [r`$2\sin\alpha\cos\beta=\sin(\alpha+\beta)+\sin(\alpha-\beta)$`, r`$2\cos\alpha\cos\beta=\cos(\alpha+\beta)+\cos(\alpha-\beta)$`, r`$2\sin\alpha\sin\beta=\cos(\alpha-\beta)-\cos(\alpha+\beta)$`] },
    { n: '複數的絕對值與共軛', h: r`$z=a+bi$`, f: r`$|z|=\sqrt{a^2+b^2}$，$\bar z=a-bi$，$z\,\bar z=|z|^2$` },
    { n: '複數的極式', f: r`$z=r(\cos\theta+i\sin\theta)$，$r=|z|$` },
    { n: '極式的乘除', f: [r`$z_1z_2=r_1r_2\left[\cos(\theta_1+\theta_2)+i\sin(\theta_1+\theta_2)\right]$`, r`$\dfrac{z_1}{z_2}=\dfrac{r_1}{r_2}\left[\cos(\theta_1-\theta_2)+i\sin(\theta_1-\theta_2)\right]$`] },
    { n: '棣美弗定理', f: r`$\left[r(\cos\theta+i\sin\theta)\right]^n=r^n(\cos n\theta+i\sin n\theta)$` },
    { n: '1 的 n 次方根', h: r`$z^n=1$`, f: r`$z_k=\cos\dfrac{2k\pi}{n}+i\sin\dfrac{2k\pi}{n}$，$k=0,1,\dots,n-1$` },
    { n: '1 的立方虛根 ω', f: r`$\omega^3=1$，$\omega^2+\omega+1=0$` },
    { n: '實係數方程式虛根成對', f: r`$a+bi$ 是根 $\Rightarrow a-bi$ 也是根` },
  ]},
  { part: '高三・選修（數甲／數乙）', elective: true, title: '平面上的線性變換', items: [
    { n: '旋轉矩陣', h: r`逆時針旋轉 $\theta$`, f: r`$\begin{bmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{bmatrix}$` },
    { n: '鏡射矩陣', h: r`對過原點、斜角 $\theta$ 的直線`, f: r`$\begin{bmatrix}\cos2\theta&\sin2\theta\\\sin2\theta&-\cos2\theta\end{bmatrix}$` },
    { n: '伸縮、推移矩陣', f: r`伸縮 $\begin{bmatrix}h&0\\0&k\end{bmatrix}$；沿 $x$ 軸推移 $\begin{bmatrix}1&k\\0&1\end{bmatrix}$` },
    { n: '變換後的面積', f: r`新面積 $=|\det A|\times$ 原面積` },
  ]},
  { part: '高三・選修（數甲／數乙）', elective: true, title: '極限與微積分', items: [
    { n: '無窮等比數列的極限', h: r`$\lim_{n\to\infty}r^n$`, f: r`$|r|<1$ 時 $=0$；$r=1$ 時 $=1$；$r>1$ 或 $r\le-1$ 發散` },
    { n: '無窮等比級數和', f: r`$a+ar+ar^2+\cdots=\dfrac{a}{1-r}$`, c: r`$|r|<1$` },
    { n: '導數的定義', f: r`$f'(a)=\lim_{h\to0}\dfrac{f(a+h)-f(a)}{h}$` },
    { n: '冪次的導函數', f: r`$(x^n)'=nx^{n-1}$，$(c)'=0$` },
    { n: '導函數的四則', f: r`$(af\pm bg)'=af'\pm bg'$，$(fg)'=f'g+fg'$` },
    { n: '一次式的 n 次方', h: r`$\left[(ax+b)^n\right]'$`, f: r`$\left[(ax+b)^n\right]'=na(ax+b)^{n-1}$` },
    { n: '切線方程式', h: r`$y=f(x)$ 在 $x=a$`, f: r`$y-f(a)=f'(a)(x-a)$` },
    { n: '遞增、遞減', f: r`$f'(x)>0$ 遞增；$f'(x)<0$ 遞減` },
    { n: '極值的判別', f: r`$f'(a)=0$ 且 $f''(a)<0$ 為極大；$f'(a)=0$ 且 $f''(a)>0$ 為極小` },
    { n: '反曲點', f: r`$f''(a)=0$ 且 $f''$ 在 $a$ 左右變號` },
    { n: '反導函數（不定積分）', f: r`$\int x^n\,dx=\dfrac{x^{n+1}}{n+1}+C$`, c: r`$n\ne-1$` },
    { n: '微積分基本定理', f: r`$\int_a^b f(x)\,dx=F(b)-F(a)$（$F'=f$）` },
    { n: '定積分的性質', f: r`$\int_a^b f+\int_b^c f=\int_a^c f$，$\int_a^b f=-\int_b^a f$` },
    { n: '兩曲線所夾面積', f: r`$\int_a^b\left|f(x)-g(x)\right|dx$` },
    { n: '黎曼和', f: r`$\int_0^1 f(x)\,dx=\lim_{n\to\infty}\dfrac1n\sum_{k=1}^{n}f\!\left(\dfrac kn\right)$` },
  ]},
];

/* 常見數值：分成幾組小表 */
const numbers = [
  { title: '根號 1 ～ 10', cols: 2, items: [
    [r`$\sqrt1$`, r`$1$`], [r`$\sqrt2$`, r`$\approx1.414$`], [r`$\sqrt3$`, r`$\approx1.732$`], [r`$\sqrt4$`, r`$2$`],
    [r`$\sqrt5$`, r`$\approx2.236$`], [r`$\sqrt6$`, r`$\approx2.449$`], [r`$\sqrt7$`, r`$\approx2.646$`], [r`$\sqrt8$`, r`$\approx2.828$`],
    [r`$\sqrt9$`, r`$3$`], [r`$\sqrt{10}$`, r`$\approx3.162$`],
  ]},
  { title: 'log 1 ～ log 10（以 10 為底）', cols: 2, items: [
    [r`$\log1$`, r`$0$`], [r`$\log2$`, r`$\approx0.3010$`], [r`$\log3$`, r`$\approx0.4771$`], [r`$\log4$`, r`$\approx0.6021$`],
    [r`$\log5$`, r`$\approx0.6990$`], [r`$\log6$`, r`$\approx0.7782$`], [r`$\log7$`, r`$\approx0.8451$`], [r`$\log8$`, r`$\approx0.9031$`],
    [r`$\log9$`, r`$\approx0.9542$`], [r`$\log10$`, r`$1$`],
  ]},
  { title: '特殊角的三角函數值', grid: {
    head: ['', r`$\sin$`, r`$\cos$`, r`$\tan$`],
    rows: [
      [r`$0^\circ$`, r`$0$`, r`$1$`, r`$0$`],
      [r`$30^\circ\ \left(\frac\pi6\right)$`, r`$\dfrac12$`, r`$\dfrac{\sqrt3}{2}$`, r`$\dfrac{\sqrt3}{3}$`],
      [r`$45^\circ\ \left(\frac\pi4\right)$`, r`$\dfrac{\sqrt2}{2}$`, r`$\dfrac{\sqrt2}{2}$`, r`$1$`],
      [r`$60^\circ\ \left(\frac\pi3\right)$`, r`$\dfrac{\sqrt3}{2}$`, r`$\dfrac12$`, r`$\sqrt3$`],
      [r`$90^\circ\ \left(\frac\pi2\right)$`, r`$1$`, r`$0$`, '不存在'],
      [r`$15^\circ$`, r`$\dfrac{\sqrt6-\sqrt2}{4}$`, r`$\dfrac{\sqrt6+\sqrt2}{4}$`, r`$2-\sqrt3$`],
      [r`$75^\circ$`, r`$\dfrac{\sqrt6+\sqrt2}{4}$`, r`$\dfrac{\sqrt6-\sqrt2}{4}$`, r`$2+\sqrt3$`],
    ],
  }},
  { title: '常數', cols: 2, items: [
    [r`$\pi$`, r`$\approx3.1416$`], [r`$e$`, r`$\approx2.718$`],
  ]},
];

module.exports = { sections, numbers };
